"""HTML rendering helpers for Xiaohongshu image pages."""

from __future__ import annotations

from html import escape
from pathlib import Path
import re
from typing import Any

from podcast_agent.reports.xhs.render.layout import balanced_extra_gap, safe_body_usable_height
from podcast_agent.reports.xhs.render.styles import render_page_css

__all__ = [
    "render_body_html",
    "render_intro_html",
    "render_measure_html",
    "render_text",
    "render_title_text",
]


def render_intro_html(*, note: dict[str, Any], width: int, height: int) -> str:
    frontmatter = note["frontmatter"]
    title = str(frontmatter.get("title") or "播客笔记")
    source = str(frontmatter.get("source") or "")
    cover_html = _render_intro_cover(note)
    return _page_html(
        width=width,
        height=height,
        body=f"""
        <main class="intro">
          {cover_html}
          <div class="kicker">{render_text("Generated by Podcast Agent")}</div>
          <h1>{render_title_text(title)}</h1>
          <p>{render_text(str(note["intro"]))}</p>
          <footer>{render_text(source)}</footer>
        </main>
        """,
    )


def render_body_html(
    *,
    note: dict[str, Any],
    blocks: list[dict[str, str]],
    width: int,
    height: int,
    content_height: float | None = None,
) -> str:
    body = "\n".join(_render_block(block, block_id=f"b{index}") for index, block in enumerate(blocks, start=1))
    extra_gap = balanced_extra_gap(
        content_height=content_height,
        block_count=len(blocks),
        usable_height=safe_body_usable_height(height),
    )
    return _page_html(
        width=width,
        height=height,
        extra_gap=extra_gap,
        body=f"<main class=\"body\"><article>{body}</article></main>",
    )


def render_measure_html(*, blocks: list[dict[str, str]], width: int, height: int) -> str:
    body = "\n".join(_render_block(block, block_id=f"b{index}") for index, block in enumerate(blocks, start=1))
    return _page_html(
        width=width,
        height=height,
        extra_gap=0,
        body=f"<main class=\"body measure\"><article>{body}</article></main>",
    )


def render_text(text: str) -> str:
    """Escape text for safe HTML rendering."""
    return escape(text)


def render_title_text(text: str, *, min_tail_chars: int = 4) -> str:
    """Escape title text and prevent a single trailing CJK character from wrapping alone."""
    escaped = escape(text)
    match = re.search(r"([\u4e00-\u9fff]{2,})([。！？!?：:，,、；;]*)$", escaped)
    if not match:
        return escaped
    cjk_tail = match.group(1)
    punctuation = match.group(2)
    protected_count = min(len(cjk_tail), min_tail_chars)
    split_at = len(cjk_tail) - protected_count
    prefix = escaped[: match.start(1)] + cjk_tail[:split_at]
    protected = cjk_tail[split_at:] + punctuation
    return f'{prefix}<span class="no-orphan">{protected}</span>'


def _render_block(block: dict[str, str], *, block_id: str) -> str:
    kind = escape(block["kind"])
    continuation = str(bool(block.get("continuation"))).lower()
    if block["kind"] == "heading":
        content = f"<h2>{render_text(_plain_heading_text(block['text']))}</h2>"
    elif block["kind"] == "quote":
        content = f"<blockquote>{render_text(block['text'])}</blockquote>"
    else:
        content = f"<p>{render_text(block['text'])}</p>"
    return f'<section class="xhs-block" data-block-id="{block_id}" data-block-kind="{kind}" data-continuation="{continuation}">{content}</section>'


def _plain_heading_text(text: str) -> str:
    return text.strip()


def _render_intro_cover(note: dict[str, Any]) -> str:
    frontmatter = note.get("frontmatter", {})
    intro_image = str(frontmatter.get("intro_image") or "").strip()
    base_dir = note.get("base_dir")
    if not intro_image or not isinstance(base_dir, Path):
        return ""
    image_path = Path(intro_image)
    if not image_path.is_absolute():
        image_path = base_dir / image_path
    if not image_path.is_file():
        return ""
    return f'<img class="intro-cover" src="{escape(image_path.resolve().as_uri())}" alt="">'


def _page_html(*, width: int, height: int, body: str, extra_gap: float = 0) -> str:
    css = render_page_css(width=width, height=height, extra_gap=extra_gap)
    return f"<!doctype html><html><head><meta charset=\"utf-8\"><style>{css}</style></head><body>{body}</body></html>"
