from pathlib import Path

from podcast_agent.reports.xhs.render.html import (
    render_body_html,
    render_intro_html,
    render_measure_html,
    render_text,
    render_title_text,
)


def test_render_intro_html_includes_intro_image_when_present(tmp_path: Path) -> None:
    cover_path = tmp_path / "cover.png"
    cover_path.write_bytes(b"fake png")
    note = {
        "frontmatter": {"title": "标题", "source": "来源", "intro_image": "./cover.png"},
        "intro": "封面导语。",
        "base_dir": tmp_path,
    }

    html = render_intro_html(note=note, width=1080, height=1440)

    assert 'class="intro-cover"' in html
    assert cover_path.resolve().as_uri() in html
    assert "Generated by Podcast Agent" in html
    assert "border-radius: 18px" in html
    assert "box-shadow: 0 24px 54px" in html
    assert ".kicker { font-size: 30px; font-weight: 700; font-style: italic" in html
    assert ".intro p { margin: 34px 0 0; font-size: 30px; line-height: 1.72; font-weight: 400; color: #4f5a55; }" in html


def test_render_body_html_uses_serif_fonts_and_smaller_italic_quotes() -> None:
    html = render_body_html(
        note={"frontmatter": {}},
        blocks=[{"kind": "quote", "text": "引用一句。"}],
        width=1080,
        height=1440,
    )

    assert 'font-family: "LXGW WenKai";' in html
    assert 'font-family: "LXGW WenKai", serif' in html
    assert ".latin" not in html
    assert "font-size: 27px; font-style: italic; line-height: 1.8" in html
    assert '<section class="xhs-block" data-block-id="b1" data-block-kind="quote" data-continuation="false"><blockquote>引用一句。</blockquote></section>' in html


def test_render_body_html_formats_plain_heading() -> None:
    html = render_body_html(
        note={"frontmatter": {}},
        blocks=[{"kind": "heading", "text": "4. 把公司变成创新机器"}],
        width=1080,
        height=1440,
    )

    assert "<h2>4. 把公司变成创新机器</h2>" in html
    assert "如何把公司变成创新机器" not in html
    assert "font-size: 34px" in html
    assert "line-height: 1.45" in html
    assert "text-wrap: balance" in html
    assert ".no-orphan { white-space: nowrap; }" in html
    assert "justify-content: flex-start" in html


def test_render_text_escapes_without_splitting_latin_runs() -> None:
    html = render_text("CUDA不是技术，OpenAI 30岁")

    assert "CUDA不是技术，OpenAI 30岁" == html


def test_render_title_text_prevents_single_trailing_cjk_character() -> None:
    html = render_title_text("AI竞争下半场：定义该做什么")

    assert html == 'AI竞争下半场：定义<span class="no-orphan">该做什么</span>'


def test_render_body_html_spreads_leftover_space_between_blocks() -> None:
    html = render_body_html(
        note={"frontmatter": {}},
        blocks=[
            {"kind": "heading", "text": "1. 观点"},
            {"kind": "paragraph", "text": "正文一"},
            {"kind": "paragraph", "text": "正文二"},
        ],
        width=1080,
        height=1440,
        content_height=900,
    )

    assert "calc(34px + 26.00px)" in html


def test_render_body_html_marks_continuation_blocks() -> None:
    html = render_body_html(
        note={"frontmatter": {}},
        blocks=[{"kind": "paragraph", "text": "后半段", "continuation": True}],
        width=1080,
        height=1440,
    )

    assert 'data-continuation="true"' in html
    assert '.xhs-block[data-continuation="true"] { margin-top: 0; }' in html


def test_render_measure_html_uses_measure_layout_and_block_ids() -> None:
    html = render_measure_html(
        blocks=[{"kind": "heading", "text": "1. 观点"}, {"kind": "paragraph", "text": "正文"}],
        width=1080,
        height=1440,
    )

    assert '<main class="body measure">' in html
    assert 'data-block-id="b1" data-block-kind="heading" data-continuation="false"' in html
    assert ".measure article { height: auto; display: block; }" in html
    assert "calc(34px + 0.00px)" in html
