from pathlib import Path

import pytest

from podcast_agent.errors import XhsReportError
from podcast_agent.reports.xhs.renderer import (
    XhsMeasuredBlock,
    balanced_extra_gap,
    clear_rendered_images,
    paginate_measured_blocks,
    parse_xhs_note,
    render_body_html,
    render_intro_html,
    render_measure_html,
    render_title_text,
    render_text,
    safe_body_usable_height,
    split_paragraph_block,
    write_pagination_debug,
)


def test_parse_xhs_note_extracts_intro_and_body_blocks(tmp_path: Path) -> None:
    note_path = tmp_path / "note.md"
    note_path.write_text(
        """---
title: "标题"
source: "来源"
url: "https://example.com"
intro_image: "./cover.png"
---

封面导语。

---

## 1. 观点

正文第一段。

> 引用一句。
""",
        encoding="utf-8",
    )

    note = parse_xhs_note(note_path)

    assert note["frontmatter"]["title"] == "标题"
    assert note["intro"] == "封面导语。"
    assert note["base_dir"] == tmp_path
    assert note["body_blocks"] == [
        {"kind": "heading", "text": "1. 观点"},
        {"kind": "paragraph", "text": "正文第一段。"},
        {"kind": "quote", "text": "引用一句。"},
    ]


def test_parse_xhs_note_requires_intro_body_separator(tmp_path: Path) -> None:
    note_path = tmp_path / "note.md"
    note_path.write_text("---\ntitle: \"标题\"\n---\n\n只有导语。\n", encoding="utf-8")

    with pytest.raises(XhsReportError, match="intro and body separated"):
        parse_xhs_note(note_path)


def test_paginate_measured_blocks_balances_sparse_last_page() -> None:
    blocks = [
        _measured("b1", "paragraph", 300),
        _measured("b2", "paragraph", 300),
        _measured("b3", "paragraph", 300),
        _measured("b4", "paragraph", 300),
    ]

    pages = paginate_measured_blocks(blocks=blocks, usable_height=1000)

    assert [[block.id for block in page] for page in pages] == [["b1", "b2"], ["b3", "b4"]]


def test_paginate_measured_blocks_moves_orphan_heading_to_next_page() -> None:
    blocks = [
        _measured("b1", "paragraph", 500),
        _measured("b2", "heading", 100),
        _measured("b3", "paragraph", 500),
    ]

    pages = paginate_measured_blocks(blocks=blocks, usable_height=700)

    assert [[block.id for block in page] for page in pages] == [["b1"], ["b2", "b3"]]


def test_paginate_measured_blocks_keeps_quote_with_previous_paragraph() -> None:
    blocks = [
        _measured("b1", "paragraph", 500),
        _measured("b2", "paragraph", 500),
        _measured("b3", "quote", 100),
    ]

    pages = paginate_measured_blocks(blocks=blocks, usable_height=1100)

    assert [[block.id for block in page] for page in pages] == [["b1", "b2", "b3"]]


def test_paginate_measured_blocks_keeps_oversized_block_on_own_page() -> None:
    blocks = [
        _measured("b1", "paragraph", 300),
        _measured("b2", "paragraph", 1200, warning="block exceeds usable page height"),
        _measured("b3", "paragraph", 300),
    ]

    pages = paginate_measured_blocks(blocks=blocks, usable_height=1000)

    assert [[block.id for block in page] for page in pages] == [["b1"], ["b2"], ["b3"]]


def test_paginate_measured_blocks_merges_sparse_adjacent_pages() -> None:
    blocks = [
        _measured("b1", "paragraph", 850),
        _measured("b2", "paragraph", 850),
        _measured("b3", "paragraph", 950),
        _measured("b4", "heading", 100),
        _measured("b5", "paragraph", 287),
        _measured("b6", "paragraph", 733),
    ]

    pages = paginate_measured_blocks(blocks=blocks, usable_height=1240)

    assert [[block.id for block in page] for page in pages][-1] == ["b4", "b5", "b6"]
    assert _page_height_for_test(pages[-1]) <= 1240


def test_paginate_measured_blocks_splits_paragraph_to_fill_previous_page() -> None:
    long_text = "第一句可以放进上一页。第二句继续解释背景。第三句留到下一页继续。第四句作为收尾。"
    blocks = [
        _measured("b1", "paragraph", 760),
        _measured("b2", "paragraph", 900, text=long_text),
        _measured("b3", "paragraph", 180),
    ]

    pages = paginate_measured_blocks(blocks=blocks, usable_height=1000)

    assert pages[0][-1].id == "b2a"
    assert pages[0][-1].split_from == "b2"
    assert pages[1][0].id == "b2b"
    assert pages[1][0].continuation is True
    assert pages[1][0].text in long_text


def test_render_intro_html_includes_intro_image_when_present(tmp_path: Path) -> None:
    cover_path = tmp_path / "cover.png"
    cover_path.write_bytes(b"fake png")
    note = {
        "frontmatter": {"title": "标题", "source": "来源", "intro_image": "./cover.png"},
        "intro": "封面导语。",
        "base_dir": tmp_path,
    }

    html = render_intro_html(note=note, width=1080, height=1440)

    assert 'class="intro-cover"' in html
    assert cover_path.resolve().as_uri() in html
    assert "Generated by Podcast Agent" in html
    assert "border-radius: 18px" in html
    assert "box-shadow: 0 24px 54px" in html
    assert ".kicker { font-size: 30px; font-weight: 700; font-style: italic" in html
    assert ".intro p { margin: 34px 0 0; font-size: 30px; line-height: 1.72; font-weight: 400; color: #4f5a55; }" in html


def test_render_body_html_uses_serif_fonts_and_smaller_italic_quotes() -> None:
    html = render_body_html(
        note={"frontmatter": {}},
        blocks=[{"kind": "quote", "text": "引用一句。"}],
        width=1080,
        height=1440,
    )

    assert 'font-family: "LXGW WenKai";' in html
    assert 'font-family: "LXGW WenKai", serif' in html
    assert ".latin" not in html
    assert "font-size: 27px; font-style: italic; line-height: 1.8" in html
    assert '<section class="xhs-block" data-block-id="b1" data-block-kind="quote" data-continuation="false"><blockquote>引用一句。</blockquote></section>' in html


def test_render_body_html_formats_plain_heading() -> None:
    html = render_body_html(
        note={"frontmatter": {}},
        blocks=[{"kind": "heading", "text": "4. 把公司变成创新机器"}],
        width=1080,
        height=1440,
    )

    assert "<h2>4. 把公司变成创新机器</h2>" in html
    assert "如何把公司变成创新机器" not in html
    assert "font-size: 34px" in html
    assert "line-height: 1.45" in html
    assert "text-wrap: balance" in html
    assert ".no-orphan { white-space: nowrap; }" in html
    assert "justify-content: flex-start" in html


def test_render_text_escapes_without_splitting_latin_runs() -> None:
    html = render_text("CUDA不是技术，OpenAI 30岁")

    assert "CUDA不是技术，OpenAI 30岁" == html


def test_render_title_text_prevents_single_trailing_cjk_character() -> None:
    html = render_title_text("AI竞争下半场：定义该做什么")

    assert html == 'AI竞争下半场：定义<span class="no-orphan">该做什么</span>'


def test_render_body_html_spreads_leftover_space_between_blocks() -> None:
    html = render_body_html(
        note={"frontmatter": {}},
        blocks=[
            {"kind": "heading", "text": "1. 观点"},
            {"kind": "paragraph", "text": "正文一"},
            {"kind": "paragraph", "text": "正文二"},
        ],
        width=1080,
        height=1440,
        content_height=900,
    )

    assert "calc(34px + 26.00px)" in html


def test_render_body_html_marks_continuation_blocks() -> None:
    html = render_body_html(
        note={"frontmatter": {}},
        blocks=[{"kind": "paragraph", "text": "后半段", "continuation": True}],
        width=1080,
        height=1440,
    )

    assert 'data-continuation="true"' in html
    assert '.xhs-block[data-continuation="true"] { margin-top: 0; }' in html


def test_balanced_extra_gap_skips_single_block_and_caps_gap() -> None:
    assert balanced_extra_gap(content_height=900, block_count=1, usable_height=1240) == 0
    assert balanced_extra_gap(content_height=1208, block_count=3, usable_height=1240) == 16
    assert balanced_extra_gap(content_height=900, block_count=3, usable_height=1240) == 26


def test_clear_rendered_images_removes_stale_intro_and_pages(tmp_path: Path) -> None:
    images_dir = tmp_path / "images"
    images_dir.mkdir()
    for name in ("intro.png", "page_1.png", "page_5.png", "cover.png"):
        (images_dir / name).write_bytes(b"old")

    clear_rendered_images(images_dir)

    assert not (images_dir / "intro.png").exists()
    assert not (images_dir / "page_1.png").exists()
    assert not (images_dir / "page_5.png").exists()
    assert (images_dir / "cover.png").exists()


def test_render_measure_html_uses_measure_layout_and_block_ids() -> None:
    html = render_measure_html(
        blocks=[{"kind": "heading", "text": "1. 观点"}, {"kind": "paragraph", "text": "正文"}],
        width=1080,
        height=1440,
    )

    assert '<main class="body measure">' in html
    assert 'data-block-id="b1" data-block-kind="heading" data-continuation="false"' in html
    assert ".measure article { height: auto; display: block; }" in html
    assert "calc(34px + 0.00px)" in html


def test_safe_body_usable_height_uses_padding_and_margin() -> None:
    assert safe_body_usable_height(1440) == 1240


def test_write_pagination_debug_writes_page_heights_and_warnings(tmp_path: Path) -> None:
    path = tmp_path / "pagination_debug.json"
    pages = [
        [_measured("b1", "paragraph", 300)],
        [_measured("b2", "paragraph", 1200, warning="block exceeds usable page height")],
    ]

    write_pagination_debug(path, width=1080, height=1440, usable_height=safe_body_usable_height(1440), pages=pages)
    text = path.read_text(encoding="utf-8")

    assert '"page_count": 2' in text
    assert '"block_ids": [' in text
    assert "block exceeds usable page height" in text


def test_write_pagination_debug_includes_split_metadata(tmp_path: Path) -> None:
    path = tmp_path / "pagination_debug.json"
    pages = [[_measured("b2b", "paragraph", 300, text="后半段", split_from="b2", split_part=2, continuation=True)]]

    write_pagination_debug(path, width=1080, height=1440, usable_height=safe_body_usable_height(1440), pages=pages)
    text = path.read_text(encoding="utf-8")

    assert '"split_from": "b2"' in text
    assert '"split_part": 2' in text
    assert '"continuation": true' in text


def test_split_paragraph_block_uses_sentence_prefix_when_possible() -> None:
    block = _measured("b1", "paragraph", 900, text="第一句可以放进去。第二句留在下一页。第三句继续。")

    split = split_paragraph_block(block, available_height=360, min_prefix_chars=4)

    assert split is not None
    head, tail = split
    assert head.text == "第一句可以放进去。"
    assert tail.text == "第二句留在下一页。第三句继续。"
    assert tail.continuation is True


def _measured(
    block_id: str,
    kind: str,
    height: float,
    warning: str | None = None,
    text: str | None = None,
    split_from: str | None = None,
    split_part: int | None = None,
    continuation: bool = False,
) -> XhsMeasuredBlock:
    value = text or block_id
    return XhsMeasuredBlock(
        id=block_id,
        kind=kind,
        text=value,
        block={"kind": kind, "text": value, "continuation": continuation},
        outer_height=height,
        warning=warning,
        split_from=split_from,
        split_part=split_part,
        continuation=continuation,
    )


def _page_height_for_test(page: list[XhsMeasuredBlock]) -> float:
    return sum(block.outer_height for block in page)
