"""Podcast-Agent CLI entrypoint."""

from podcast_agent.cli.commands import (
    FullBatchCase,
    FullBatchCaseResult,
    app,
    build_default_aliyun_transcriber,
    compose_xhs_report,
    extract_evidence,
    generate_outline,
    generate_summary,
    generate_viewpoints,
    load_full_batch_cases,
    prepare_xhs_cover,
    render_markdown_report,
    render_pdf_report,
    render_xhs_images,
    resolve_report_intent,
    run_full_batch_case,
    run_pipeline,
    write_report_intent,
    YoutubeTranscriptFetcher,
)

__all__ = [
    "FullBatchCase",
    "FullBatchCaseResult",
    "YoutubeTranscriptFetcher",
    "app",
    "build_default_aliyun_transcriber",
    "compose_xhs_report",
    "extract_evidence",
    "generate_outline",
    "generate_summary",
    "generate_viewpoints",
    "load_full_batch_cases",
    "prepare_xhs_cover",
    "render_markdown_report",
    "render_pdf_report",
    "render_xhs_images",
    "resolve_report_intent",
    "run_full_batch_case",
    "run_pipeline",
    "write_report_intent",
]
